apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Redis
  name: ocp-redis
spec:
  dockerImageRepository: "redis"
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: redis:4.0.2
    importPolicy: {}
    name: "4.0.2"
  - annotations: null
    from:
      kind: ImageStreamTag
      name: "4.0.2"
    importPolicy: {}
    name: "4.0"
  - annotations: null
    from:
      kind: DockerImage
      name: redis:latest
    importPolicy: {}
    name: latest

